// The report markdown renderer now parses through the shared @shared/markdown
// module (also used by the chat view). These tests pin the HTML the report
// exporter produces for the constructs real reports use — headings, bold,
// bullets, numbered lists, tables, inline code, multi-line paragraphs — so the
// shared parser can never silently change what a exported PDF/Word/HTML report
// looks like.
import test from 'node:test'
import assert from 'node:assert/strict'
import { buildReportHtml, reportMarkdownToHtml } from '../src/main/jobs/reportArtifacts.ts'
import { parseInlineMarkdown, parseMarkdownBlocks } from '../src/shared/markdown.ts'

test('headings, bold, and paragraphs render as before', () => {
  const html = reportMarkdownToHtml('## What the day was about\n\nTracked time came to **4h 11m**, and *most* of it in one app.')
  assert.equal(
    html,
    '<h2>What the day was about</h2>\n<p>Tracked time came to <strong>4h 11m</strong>, and <em>most</em> of it in one app.</p>',
  )
})

test('bullet and numbered lists render as before', () => {
  const html = reportMarkdownToHtml('- **Research** — 1h 20m\n- A second item\n\n1. First step\n2. Second step')
  assert.equal(
    html,
    '<ul><li><strong>Research</strong> — 1h 20m</li><li>A second item</li></ul>\n<ol><li>First step</li><li>Second step</li></ol>',
  )
})

test('tables render as before, with inline markdown in cells', () => {
  const html = reportMarkdownToHtml('| Client | Hours |\n| --- | --- |\n| **Acme** | 12.5 |')
  assert.equal(
    html,
    '<table><thead><tr><th>Client</th><th>Hours</th></tr></thead><tbody><tr><td><strong>Acme</strong></td><td>12.5</td></tr></tbody></table>',
  )
})

test('multi-line paragraphs join with <br/> and HTML is escaped', () => {
  const html = reportMarkdownToHtml('Up 8% & above <average>.\nSecond line.')
  assert.equal(html, '<p>Up 8% &amp; above &lt;average&gt;.<br/>Second line.</p>')
})

test('inline code renders and its content is escaped', () => {
  const html = reportMarkdownToHtml('Reviewed `src/main` & `a<b`.')
  assert.equal(html, '<p>Reviewed <code>src/main</code> &amp; <code>a&lt;b</code>.</p>')
})

test('underscores never italicize — evidence names stay literal', () => {
  const html = reportMarkdownToHtml('Recovered from focus_events and app_sessions rows.')
  assert.equal(html, '<p>Recovered from focus_events and app_sessions rows.</p>')
})

test('a heading glued to its content keeps both (heading + body)', () => {
  const html = reportMarkdownToHtml('## Highlights\n- Shipped the thing')
  assert.equal(html, '<h2>Highlights</h2>\n<ul><li>Shipped the thing</li></ul>')
})

test('buildReportHtml drops the subtitle when it repeats the title', () => {
  const html = buildReportHtml('June 29, 2026', 'June 29, 2026', 'Body.')
  assert.ok(!html.includes('class="subtitle"'))
  assert.ok(html.includes('<footer>Generated by Daylens.</footer>'))

  const withSubtitle = buildReportHtml('June 29, 2026', '2026-06-29', 'Body.')
  assert.ok(withSubtitle.includes('<p class="subtitle">2026-06-29</p>'))
  assert.ok(withSubtitle.includes('<footer>Generated by Daylens for 2026-06-29.</footer>'))
})

test('parseInlineMarkdown tokenizes bold, em, code, and plain text', () => {
  assert.deepEqual(parseInlineMarkdown('a **b** *c* `d` e'), [
    { type: 'text', text: 'a ' },
    { type: 'strong', text: 'b' },
    { type: 'text', text: ' ' },
    { type: 'em', text: 'c' },
    { type: 'text', text: ' ' },
    { type: 'code', text: 'd' },
    { type: 'text', text: ' e' },
  ])
})

test('parseMarkdownBlocks classifies every block shape', () => {
  const nodes = parseMarkdownBlocks('# Title\n\n- one\n- two\n\n1. a\n\n| H |\n| --- |\n| c |\n\nplain')
  assert.deepEqual(nodes.map((node) => node.type), ['heading', 'bullet_list', 'ordered_list', 'table', 'paragraph'])
})
