// Auto-generated by scripts/generate-changelog-page-data.mjs
export const generatedChangelogData = {
  "generatedAt": "2026-04-19T21:56:11.344Z",
  "surfaces": [
    {
      "id": "web",
      "name": "Web companion",
      "description": "Marketing site, web companion access, linking, recovery, and public product pages.",
      "version": "0.2.4",
      "repoPath": "/Users/tonny/Dev-Personal/daylens-web",
      "latestCommitDateTime": "2026-04-19T22:29:46+02:00",
      "latestCommitDate": "2026-04-19",
      "latestCommitHash": "5cc900c",
      "recentCommits": [
        {
          "dateTime": "2026-04-19T22:29:46+02:00",
          "date": "2026-04-19",
          "shortHash": "5cc900c",
          "subject": "Fix landing page styling regression"
        },
        {
          "dateTime": "2026-04-19T22:19:33+02:00",
          "date": "2026-04-19",
          "shortHash": "94f554a",
          "subject": "Merge branch 'codex/final-launch-closure' into main"
        },
        {
          "dateTime": "2026-04-19T22:17:33+02:00",
          "date": "2026-04-19",
          "shortHash": "17f62f9",
          "subject": "Refresh public product status copy"
        },
        {
          "dateTime": "2026-04-19T20:44:17+02:00",
          "date": "2026-04-19",
          "shortHash": "55ab7ab",
          "subject": "fix: point mac download to unified desktop repo"
        },
        {
          "dateTime": "2026-04-19T20:44:17+02:00",
          "date": "2026-04-19",
          "shortHash": "73f3b8a",
          "subject": "fix: point mac download to unified desktop repo"
        },
        {
          "dateTime": "2026-04-18T23:35:33+02:00",
          "date": "2026-04-18",
          "shortHash": "122aa97",
          "subject": "Simplify landing page hierarchy"
        },
        {
          "dateTime": "2026-04-18T22:32:01+02:00",
          "date": "2026-04-18",
          "shortHash": "e7d11ca",
          "subject": "Simplify landing page copy and balance layout"
        },
        {
          "dateTime": "2026-04-18T22:12:24+02:00",
          "date": "2026-04-18",
          "shortHash": "9f22992",
          "subject": "docs: align public launch surfaces"
        },
        {
          "dateTime": "2026-04-18T22:08:08+02:00",
          "date": "2026-04-18",
          "shortHash": "80656e1",
          "subject": "Polish landing page interactions and layout"
        },
        {
          "dateTime": "2026-04-18T21:22:28+02:00",
          "date": "2026-04-18",
          "shortHash": "e3aa595",
          "subject": "fix: align linux marketing with unified transition"
        }
      ],
      "releases": [
        {
          "id": "web-0.2.4",
          "version": "0.2.4",
          "date": "2026-04-19",
          "title": "The public changelog sync now reads curated",
          "intro": [
            "Web companion v0.2.4 centers on the public changelog sync now reads curated.",
            "The public changelog sync now reads curated release notes from the unified desktop repo and can link each desktop surface to the matching GitHub release page.",
            "Changelog surface definitions now follow the unified Daylens desktop repo instead of the retired multi-repo macOS, Windows, and Linux split."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "The public changelog sync now reads curated release notes from the unified desktop repo and can link each desktop surface to the matching GitHub release page"
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Changelog surface definitions now follow the unified Daylens desktop repo instead of the retired multi-repo macOS, Windows, and Linux split",
                "The website changelog now consumes curated entries for the web surface too, so public release notes stop drifting from shipped versions"
              ]
            },
            {
              "label": "Fixes",
              "items": [
                "The changelog sync script no longer expects missing CHANGELOG.md files from obsolete repo paths"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens-web/blob/main/CHANGELOG.md",
          "linkLabel": "View source changelog"
        },
        {
          "id": "web-0.2.3",
          "version": "0.2.3",
          "date": "2026-04-19",
          "title": "Public status copy now follows the unified",
          "intro": [
            "Web companion v0.2.3 centers on public status copy now follows the unified.",
            "Public status copy now follows the unified desktop truth instead of synthetic release filler.",
            "Linux, recap, and provider-backed AI status notes now separate implemented work from pending validation more clearly."
          ],
          "sections": [
            {
              "label": "Improvements",
              "items": [
                "Public status copy now follows the unified desktop truth instead of synthetic release filler",
                "Linux, recap, and provider-backed AI status notes now separate implemented work from pending validation more clearly"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens-web/blob/main/CHANGELOG.md",
          "linkLabel": "View source changelog"
        }
      ]
    },
    {
      "id": "mac",
      "name": "macOS app",
      "description": "Unified desktop macOS release with the shared timeline, AI, recap, and installer work.",
      "version": "1.0.27",
      "repoPath": "/Users/tonny/Dev-Personal/daylens",
      "latestCommitDateTime": "2026-04-19T22:25:58+02:00",
      "latestCommitDate": "2026-04-19",
      "latestCommitHash": "1df606a",
      "recentCommits": [
        {
          "dateTime": "2026-04-19T22:25:58+02:00",
          "date": "2026-04-19",
          "shortHash": "1df606a",
          "subject": "feat: polish install flow recap and parity guidance"
        },
        {
          "dateTime": "2026-04-19T19:24:29+02:00",
          "date": "2026-04-19",
          "shortHash": "41fc89a",
          "subject": "docs: reflect live unified 1.0.26 release"
        },
        {
          "dateTime": "2026-04-19T19:23:36+02:00",
          "date": "2026-04-19",
          "shortHash": "0ef99b9",
          "subject": "release: keep updater metadata names in notes"
        },
        {
          "dateTime": "2026-04-19T19:11:29+02:00",
          "date": "2026-04-19",
          "shortHash": "44b3e82",
          "subject": "release: fix notes generation on hosted runners"
        },
        {
          "dateTime": "2026-04-19T19:06:20+02:00",
          "date": "2026-04-19",
          "shortHash": "e6af535",
          "subject": "release: unify shared release downloads"
        },
        {
          "dateTime": "2026-04-19T15:51:15+02:00",
          "date": "2026-04-19",
          "shortHash": "2035779",
          "subject": "Merge pull request #9 from irachrist1/codex/launch-integration"
        },
        {
          "dateTime": "2026-04-19T01:11:25+02:00",
          "date": "2026-04-19",
          "shortHash": "2ad3043",
          "subject": "ci: publish releases on shared version tags"
        },
        {
          "dateTime": "2026-04-19T00:51:36+02:00",
          "date": "2026-04-19",
          "shortHash": "992f2a5",
          "subject": "docs: update final launch gate snapshot"
        },
        {
          "dateTime": "2026-04-19T00:26:06+02:00",
          "date": "2026-04-19",
          "shortHash": "5c82760",
          "subject": "fix: harden CLI provider launches and clear prod advisories"
        },
        {
          "dateTime": "2026-04-18T23:59:31+02:00",
          "date": "2026-04-18",
          "shortHash": "7079bae",
          "subject": "launch: integrate readiness branch and harden CI"
        }
      ],
      "releases": [
        {
          "id": "mac-1.0.27",
          "version": "1.0.27",
          "date": "2026-04-19",
          "title": "Snapshot v2 exports now include recap summaries",
          "intro": [
            "macOS app v1.0.27 centers on snapshot v2 exports now include recap summaries.",
            "Snapshot v2 exports now include recap summaries, focus score v2 breakdowns, work blocks, standout artifacts, entity rollups, and Linux as a first-class snapshot platform for downstream Daylens surfaces.",
            "AI thread naming now uses deterministic intent heuristics for reports, focus flows, and entity questions instead of defaulting to generic prompt fragments."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "Snapshot v2 exports now include recap summaries, focus score v2 breakdowns, work blocks, standout artifacts, entity rollups, and Linux as a first-class snapshot platform for downstream Daylens surfaces",
                "AI thread naming now uses deterministic intent heuristics for reports, focus flows, and entity questions instead of defaulting to generic prompt fragments"
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Monthly recap comparisons now use matched elapsed-day windows so longer months do not invent a gain over shorter previous months",
                "Recap workstream rankings now keep dominant unnamed work visible when attribution is still weak instead of overstating named coverage"
              ]
            },
            {
              "label": "Fixes",
              "items": [
                "Weak AI thread titles now upgrade after the first grounded answer resolves intent, so chats do not stay stuck on New chat or filler-led snippets"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.27",
          "linkLabel": "View release"
        },
        {
          "id": "mac-1.0.26",
          "version": "1.0.26",
          "date": "2026-04-19",
          "title": "Persistent AI threads and artifact storage inside",
          "intro": [
            "macOS app v1.0.26 centers on persistent ai threads and artifact storage inside.",
            "Persistent AI threads and artifact storage inside the AI surface.",
            "A deterministic daily, weekly, and monthly recap card inside the AI surface."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "Persistent AI threads and artifact storage inside the AI surface",
                "A deterministic daily, weekly, and monthly recap card inside the AI surface",
                "Install-flow, onboarding, and shell polish across the shared desktop app"
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Cross-platform parity guidance now reflects the unified desktop repo more honestly across macOS, Windows, and Linux"
              ]
            },
            {
              "label": "Fixes",
              "items": [
                "Shared release notes now keep updater metadata filenames consistent across platform downloads"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.26",
          "linkLabel": "View release"
        }
      ]
    },
    {
      "id": "windows",
      "name": "Windows app",
      "description": "Unified desktop Windows release with shared updater, tracking, recap, and AI behavior.",
      "version": "1.0.27",
      "repoPath": "/Users/tonny/Dev-Personal/daylens",
      "latestCommitDateTime": "2026-04-19T22:25:58+02:00",
      "latestCommitDate": "2026-04-19",
      "latestCommitHash": "1df606a",
      "recentCommits": [
        {
          "dateTime": "2026-04-19T22:25:58+02:00",
          "date": "2026-04-19",
          "shortHash": "1df606a",
          "subject": "feat: polish install flow recap and parity guidance"
        },
        {
          "dateTime": "2026-04-19T19:24:29+02:00",
          "date": "2026-04-19",
          "shortHash": "41fc89a",
          "subject": "docs: reflect live unified 1.0.26 release"
        },
        {
          "dateTime": "2026-04-19T19:23:36+02:00",
          "date": "2026-04-19",
          "shortHash": "0ef99b9",
          "subject": "release: keep updater metadata names in notes"
        },
        {
          "dateTime": "2026-04-19T19:11:29+02:00",
          "date": "2026-04-19",
          "shortHash": "44b3e82",
          "subject": "release: fix notes generation on hosted runners"
        },
        {
          "dateTime": "2026-04-19T19:06:20+02:00",
          "date": "2026-04-19",
          "shortHash": "e6af535",
          "subject": "release: unify shared release downloads"
        },
        {
          "dateTime": "2026-04-19T15:51:15+02:00",
          "date": "2026-04-19",
          "shortHash": "2035779",
          "subject": "Merge pull request #9 from irachrist1/codex/launch-integration"
        },
        {
          "dateTime": "2026-04-19T01:11:25+02:00",
          "date": "2026-04-19",
          "shortHash": "2ad3043",
          "subject": "ci: publish releases on shared version tags"
        },
        {
          "dateTime": "2026-04-19T00:51:36+02:00",
          "date": "2026-04-19",
          "shortHash": "992f2a5",
          "subject": "docs: update final launch gate snapshot"
        },
        {
          "dateTime": "2026-04-19T00:26:06+02:00",
          "date": "2026-04-19",
          "shortHash": "5c82760",
          "subject": "fix: harden CLI provider launches and clear prod advisories"
        },
        {
          "dateTime": "2026-04-18T23:59:31+02:00",
          "date": "2026-04-18",
          "shortHash": "7079bae",
          "subject": "launch: integrate readiness branch and harden CI"
        }
      ],
      "releases": [
        {
          "id": "windows-1.0.27",
          "version": "1.0.27",
          "date": "2026-04-19",
          "title": "Snapshot v2 exports now include recap summaries",
          "intro": [
            "Windows app v1.0.27 centers on snapshot v2 exports now include recap summaries.",
            "Snapshot v2 exports now include recap summaries, focus score v2 breakdowns, work blocks, standout artifacts, entity rollups, and Linux as a first-class snapshot platform for downstream Daylens surfaces.",
            "AI thread naming now uses deterministic intent heuristics for reports, focus flows, and entity questions instead of defaulting to generic prompt fragments."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "Snapshot v2 exports now include recap summaries, focus score v2 breakdowns, work blocks, standout artifacts, entity rollups, and Linux as a first-class snapshot platform for downstream Daylens surfaces",
                "AI thread naming now uses deterministic intent heuristics for reports, focus flows, and entity questions instead of defaulting to generic prompt fragments"
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Monthly recap comparisons now use matched elapsed-day windows so longer months do not invent a gain over shorter previous months",
                "Recap workstream rankings now keep dominant unnamed work visible when attribution is still weak instead of overstating named coverage"
              ]
            },
            {
              "label": "Fixes",
              "items": [
                "Weak AI thread titles now upgrade after the first grounded answer resolves intent, so chats do not stay stuck on New chat or filler-led snippets"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.27",
          "linkLabel": "View release"
        },
        {
          "id": "windows-1.0.26",
          "version": "1.0.26",
          "date": "2026-04-19",
          "title": "Persistent AI threads and artifact storage inside",
          "intro": [
            "Windows app v1.0.26 centers on persistent ai threads and artifact storage inside.",
            "Persistent AI threads and artifact storage inside the AI surface.",
            "A deterministic daily, weekly, and monthly recap card inside the AI surface."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "Persistent AI threads and artifact storage inside the AI surface",
                "A deterministic daily, weekly, and monthly recap card inside the AI surface",
                "Install-flow, onboarding, and shell polish across the shared desktop app"
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Cross-platform parity guidance now reflects the unified desktop repo more honestly across macOS, Windows, and Linux"
              ]
            },
            {
              "label": "Fixes",
              "items": [
                "Shared release notes now keep updater metadata filenames consistent across platform downloads"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.26",
          "linkLabel": "View release"
        }
      ]
    },
    {
      "id": "linux",
      "name": "Linux app",
      "description": "Unified desktop Linux release with AppImage, DEB, and RPM packaging from the shared repo.",
      "version": "1.0.27",
      "repoPath": "/Users/tonny/Dev-Personal/daylens",
      "latestCommitDateTime": "2026-04-19T22:25:58+02:00",
      "latestCommitDate": "2026-04-19",
      "latestCommitHash": "1df606a",
      "recentCommits": [
        {
          "dateTime": "2026-04-19T22:25:58+02:00",
          "date": "2026-04-19",
          "shortHash": "1df606a",
          "subject": "feat: polish install flow recap and parity guidance"
        },
        {
          "dateTime": "2026-04-19T19:24:29+02:00",
          "date": "2026-04-19",
          "shortHash": "41fc89a",
          "subject": "docs: reflect live unified 1.0.26 release"
        },
        {
          "dateTime": "2026-04-19T19:23:36+02:00",
          "date": "2026-04-19",
          "shortHash": "0ef99b9",
          "subject": "release: keep updater metadata names in notes"
        },
        {
          "dateTime": "2026-04-19T19:11:29+02:00",
          "date": "2026-04-19",
          "shortHash": "44b3e82",
          "subject": "release: fix notes generation on hosted runners"
        },
        {
          "dateTime": "2026-04-19T19:06:20+02:00",
          "date": "2026-04-19",
          "shortHash": "e6af535",
          "subject": "release: unify shared release downloads"
        },
        {
          "dateTime": "2026-04-19T15:51:15+02:00",
          "date": "2026-04-19",
          "shortHash": "2035779",
          "subject": "Merge pull request #9 from irachrist1/codex/launch-integration"
        },
        {
          "dateTime": "2026-04-19T01:11:25+02:00",
          "date": "2026-04-19",
          "shortHash": "2ad3043",
          "subject": "ci: publish releases on shared version tags"
        },
        {
          "dateTime": "2026-04-19T00:51:36+02:00",
          "date": "2026-04-19",
          "shortHash": "992f2a5",
          "subject": "docs: update final launch gate snapshot"
        },
        {
          "dateTime": "2026-04-19T00:26:06+02:00",
          "date": "2026-04-19",
          "shortHash": "5c82760",
          "subject": "fix: harden CLI provider launches and clear prod advisories"
        },
        {
          "dateTime": "2026-04-18T23:59:31+02:00",
          "date": "2026-04-18",
          "shortHash": "7079bae",
          "subject": "launch: integrate readiness branch and harden CI"
        }
      ],
      "releases": [
        {
          "id": "linux-1.0.27",
          "version": "1.0.27",
          "date": "2026-04-19",
          "title": "Snapshot v2 exports now include recap summaries",
          "intro": [
            "Linux app v1.0.27 centers on snapshot v2 exports now include recap summaries.",
            "Snapshot v2 exports now include recap summaries, focus score v2 breakdowns, work blocks, standout artifacts, entity rollups, and Linux as a first-class snapshot platform for downstream Daylens surfaces.",
            "AI thread naming now uses deterministic intent heuristics for reports, focus flows, and entity questions instead of defaulting to generic prompt fragments."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "Snapshot v2 exports now include recap summaries, focus score v2 breakdowns, work blocks, standout artifacts, entity rollups, and Linux as a first-class snapshot platform for downstream Daylens surfaces",
                "AI thread naming now uses deterministic intent heuristics for reports, focus flows, and entity questions instead of defaulting to generic prompt fragments"
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Monthly recap comparisons now use matched elapsed-day windows so longer months do not invent a gain over shorter previous months",
                "Recap workstream rankings now keep dominant unnamed work visible when attribution is still weak instead of overstating named coverage"
              ]
            },
            {
              "label": "Fixes",
              "items": [
                "Weak AI thread titles now upgrade after the first grounded answer resolves intent, so chats do not stay stuck on New chat or filler-led snippets"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.27",
          "linkLabel": "View release"
        },
        {
          "id": "linux-1.0.26",
          "version": "1.0.26",
          "date": "2026-04-19",
          "title": "Persistent AI threads and artifact storage inside",
          "intro": [
            "Linux app v1.0.26 centers on persistent ai threads and artifact storage inside.",
            "Persistent AI threads and artifact storage inside the AI surface.",
            "A deterministic daily, weekly, and monthly recap card inside the AI surface."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "Persistent AI threads and artifact storage inside the AI surface",
                "A deterministic daily, weekly, and monthly recap card inside the AI surface",
                "Install-flow, onboarding, and shell polish across the shared desktop app"
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Cross-platform parity guidance now reflects the unified desktop repo more honestly across macOS, Windows, and Linux"
              ]
            },
            {
              "label": "Fixes",
              "items": [
                "Shared release notes now keep updater metadata filenames consistent across platform downloads"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.26",
          "linkLabel": "View release"
        }
      ]
    }
  ]
} as const;
