// Auto-generated by scripts/generate-changelog-page-data.mjs
export const generatedChangelogData = {
  "generatedAt": "2026-04-24T05:21:14.359Z",
  "surfaces": [
    {
      "id": "web",
      "name": "Web companion",
      "description": "Marketing site, web companion access, linking, recovery, and public product pages.",
      "version": "0.2.4",
      "repoPath": "/Users/tonny/Dev-Personal/daylens-web",
      "latestCommitDateTime": "2026-04-23T21:30:57+02:00",
      "latestCommitDate": "2026-04-23",
      "latestCommitHash": "cc133c3",
      "recentCommits": [
        {
          "dateTime": "2026-04-23T21:30:57+02:00",
          "date": "2026-04-23",
          "shortHash": "cc133c3",
          "subject": "chore(deploy): retrigger with verified git author"
        },
        {
          "dateTime": "2026-04-23T21:25:52+02:00",
          "date": "2026-04-23",
          "shortHash": "3811a56",
          "subject": "fix(updater): add public update feed and asset proxy"
        },
        {
          "dateTime": "2026-04-22T17:47:37+02:00",
          "date": "2026-04-22",
          "shortHash": "f8a7eef",
          "subject": "fix(ai-chat): center composer text vertically"
        },
        {
          "dateTime": "2026-04-22T17:31:22+02:00",
          "date": "2026-04-22",
          "shortHash": "db4b99b",
          "subject": "feat(ai-chat): polish settings and archive threads"
        },
        {
          "dateTime": "2026-04-22T17:31:22+02:00",
          "date": "2026-04-22",
          "shortHash": "b3de32e",
          "subject": "feat(ai-chat): render markdown and tighten chat shell"
        },
        {
          "dateTime": "2026-04-22T16:58:04+02:00",
          "date": "2026-04-22",
          "shortHash": "72f28a2",
          "subject": "Widen topPageValidator to unblock deploy against stale seed row"
        },
        {
          "dateTime": "2026-04-22T16:38:49+02:00",
          "date": "2026-04-22",
          "shortHash": "c00d37e",
          "subject": "fix(downloads): avoid release API stampede"
        },
        {
          "dateTime": "2026-04-22T14:44:40+02:00",
          "date": "2026-04-22",
          "shortHash": "fac9a56",
          "subject": "fix(downloads): avoid stale release API cache"
        },
        {
          "dateTime": "2026-04-22T14:19:23+02:00",
          "date": "2026-04-22",
          "shortHash": "2e45acd",
          "subject": "fix(downloads): point site at live unified releases"
        },
        {
          "dateTime": "2026-04-22T13:06:23+02:00",
          "date": "2026-04-22",
          "shortHash": "d27becb",
          "subject": "Move BYO Anthropic key off browser, onto encrypted Convex row"
        }
      ],
      "releases": [
        {
          "id": "web-0.2.4",
          "version": "0.2.4",
          "date": "2026-04-19",
          "title": "The public changelog sync now reads curated",
          "intro": [
            "Web companion v0.2.4 centers on the public changelog sync now reads curated.",
            "The public changelog sync now reads curated release notes from the unified desktop repo and can link each desktop surface to the matching GitHub release page.",
            "Changelog surface definitions now follow the unified Daylens desktop repo instead of the retired multi-repo macOS, Windows, and Linux split."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "The public changelog sync now reads curated release notes from the unified desktop repo and can link each desktop surface to the matching GitHub release page"
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Changelog surface definitions now follow the unified Daylens desktop repo instead of the retired multi-repo macOS, Windows, and Linux split",
                "The website changelog now consumes curated entries for the web surface too, so public release notes stop drifting from shipped versions"
              ]
            },
            {
              "label": "Fixes",
              "items": [
                "The changelog sync script no longer expects missing CHANGELOG.md files from obsolete repo paths"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens-web/blob/main/CHANGELOG.md",
          "linkLabel": "View source changelog"
        },
        {
          "id": "web-0.2.3",
          "version": "0.2.3",
          "date": "2026-04-19",
          "title": "Public status copy now follows the unified",
          "intro": [
            "Web companion v0.2.3 centers on public status copy now follows the unified.",
            "Public status copy now follows the unified desktop truth instead of synthetic release filler.",
            "Linux, recap, and provider-backed AI status notes now separate implemented work from pending validation more clearly."
          ],
          "sections": [
            {
              "label": "Improvements",
              "items": [
                "Public status copy now follows the unified desktop truth instead of synthetic release filler",
                "Linux, recap, and provider-backed AI status notes now separate implemented work from pending validation more clearly"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens-web/blob/main/CHANGELOG.md",
          "linkLabel": "View source changelog"
        }
      ]
    },
    {
      "id": "mac",
      "name": "macOS app",
      "description": "Unified desktop macOS release with the shared timeline, AI, recap, and installer work.",
      "version": "1.0.30",
      "repoPath": "/Users/tonny/Dev-Personal/daylens",
      "latestCommitDateTime": "2026-04-24T07:21:03+02:00",
      "latestCommitDate": "2026-04-24",
      "latestCommitHash": "970041e",
      "recentCommits": [
        {
          "dateTime": "2026-04-24T07:21:03+02:00",
          "date": "2026-04-24",
          "shortHash": "970041e",
          "subject": "chore(release): prepare v1.0.31"
        },
        {
          "dateTime": "2026-04-24T06:06:21+02:00",
          "date": "2026-04-24",
          "shortHash": "cd771bc",
          "subject": "docs: Add execution plan, codebase overview, and updated product docs"
        },
        {
          "dateTime": "2026-04-24T06:06:15+02:00",
          "date": "2026-04-24",
          "shortHash": "e0c75ae",
          "subject": "feat(updater): Remote update feed with version comparison utilities"
        },
        {
          "dateTime": "2026-04-24T06:06:08+02:00",
          "date": "2026-04-24",
          "shortHash": "3d7ad0e",
          "subject": "feat(threads): Delete artifacts on thread deletion; reuse empty draft threads"
        },
        {
          "dateTime": "2026-04-24T06:05:27+02:00",
          "date": "2026-04-24",
          "shortHash": "897a53d",
          "subject": "feat(search): Add FTS5 search layer (Task A)"
        },
        {
          "dateTime": "2026-04-24T05:09:46+02:00",
          "date": "2026-04-24",
          "shortHash": "3a71389",
          "subject": "Wire onboarding goals into day context"
        },
        {
          "dateTime": "2026-04-24T05:09:28+02:00",
          "date": "2026-04-24",
          "shortHash": "db8f4b5",
          "subject": "Rework focus score v2"
        },
        {
          "dateTime": "2026-04-24T05:09:17+02:00",
          "date": "2026-04-24",
          "shortHash": "e915165",
          "subject": "Wire user name capture"
        },
        {
          "dateTime": "2026-04-23T12:44:49+02:00",
          "date": "2026-04-23",
          "shortHash": "fbef6bb",
          "subject": "chore(release): prepare v1.0.30"
        },
        {
          "dateTime": "2026-04-23T11:14:14+02:00",
          "date": "2026-04-23",
          "shortHash": "149eb7b",
          "subject": "fix(updater): in-place install for ad-hoc macOS + clean HTML release notes"
        }
      ],
      "releases": [
        {
          "id": "mac-1.0.31",
          "version": "1.0.31",
          "date": "2026-04-24",
          "title": "Full-text search across your entire history",
          "intro": [
            "macOS app v1.0.31 centers on full-text search across your entire history.",
            "Full-text search across your entire history — type any word into the new search box in the AI view and get every matching app session, work block, browser page, and AI artifact, sorted by time with highlighted excerpts. No AI involved — pure local SQLite FTS5.",
            "Your name in Daylens — set a display name in onboarding or Settings and the AI will use it in every response instead of the generic fallback."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "Full-text search across your entire history — type any word into the new search box in the AI view and get every matching app session, work block, browser page, and AI artifact, sorted by time with highlighted excerpts. No AI involved — pure local SQLite FTS5.",
                "Your name in Daylens — set a display name in onboarding or Settings and the AI will use it in every response instead of the generic fallback.",
                "Goals now shape your AI context — picking \"less distractions\" during onboarding adds a live distraction summary (minutes + top domains) to every AI response. Picking \"deep work\" adds your deep-work percentage and longest streak."
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Honest focus score — the old formula returned ~20 even on idle days. The new score is a single percentage: time in focused deep-work sessions (25+ continuous minutes) divided by total active time. Returns \"Not enough data\" instead of a fake number when you haven't tracked enough yet.",
                "Thread deletion now removes attached artifact files from disk instead of only cleaning the database row.",
                "Creating a new chat reuses an existing empty thread instead of accumulating blank drafts."
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.31",
          "linkLabel": "View release"
        },
        {
          "id": "mac-1.0.30",
          "version": "1.0.30",
          "date": "2026-04-23",
          "title": "MacOS updates now avoid the broken Squirrel",
          "intro": [
            "macOS app v1.0.30 centers on macos updates now avoid the broken squirrel.",
            "macOS updates now avoid the broken Squirrel.Mac install path on ad-hoc signed builds by downloading the release ZIP directly, swapping the app bundle in place, and relaunching.",
            "Release notes now strip HTML tags cleanly so GitHub-rendered changelog text no longer leaks raw markup into the update banner."
          ],
          "sections": [
            {
              "label": "Fixes",
              "items": [
                "macOS updates now avoid the broken Squirrel.Mac install path on ad-hoc signed builds by downloading the release ZIP directly, swapping the app bundle in place, and relaunching",
                "Release notes now strip HTML tags cleanly so GitHub-rendered changelog text no longer leaks raw markup into the update banner"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.30",
          "linkLabel": "View release"
        },
        {
          "id": "mac-1.0.29",
          "version": "1.0.29",
          "date": "2026-04-20",
          "title": "Rewrote the in-DMG Start Here",
          "intro": [
            "macOS app v1.0.29 centers on rewrote the in-dmg start here.",
            "Rewrote the in-DMG Start Here.txt (formerly If Daylens is \"damaged\" - READ ME.txt) for non-technical users: action-first three-step install, visual mockup of the first-launch Gatekeeper prompt, numbered Open Anyway steps, and Homebrew shown as an optional shortcut rather than the fallback.",
            "docs/INSTALL.md leads with the current first-launch flow (the \"Not Opened\" Gatekeeper prompt that appears after the v1.0.28 ad-hoc re-sign), and demotes the legacy \"damaged\" dialog fix to a troubleshooting section for anyone still on an older DMG."
          ],
          "sections": [
            {
              "label": "Improvements",
              "items": [
                "Rewrote the in-DMG Start Here.txt (formerly If Daylens is \"damaged\" - READ ME.txt) for non-technical users: action-first three-step install, visual mockup of the first-launch Gatekeeper prompt, numbered Open Anyway steps, and Homebrew shown as an optional shortcut rather than the fallback",
                "docs/INSTALL.md leads with the current first-launch flow (the \"Not Opened\" Gatekeeper prompt that appears after the v1.0.28 ad-hoc re-sign), and demotes the legacy \"damaged\" dialog fix to a troubleshooting section for anyone still on an older DMG"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.29",
          "linkLabel": "View release"
        },
        {
          "id": "mac-1.0.28",
          "version": "1.0.28",
          "date": "2026-04-20",
          "title": "MacOS DMG no longer triggers the \"Daylens",
          "intro": [
            "macOS app v1.0.28 centers on macos dmg no longer triggers the \"daylens.",
            "macOS DMG no longer triggers the \"Daylens is damaged and can't be opened\" dialog on Finder double-click: the release pipeline now re-signs the bundle ad-hoc with codesign --force --deep --sign - in an afterSign hook, producing a complete signature with sealed resources that Gatekeeper can verify.",
            "Release workflow auto-detects whether Developer ID credentials are present; without them it builds an ad-hoc signed DMG instead of failing the \"Require signing and notarization credentials\" gate."
          ],
          "sections": [
            {
              "label": "Fixes",
              "items": [
                "macOS DMG no longer triggers the \"Daylens is damaged and can't be opened\" dialog on Finder double-click: the release pipeline now re-signs the bundle ad-hoc with codesign --force --deep --sign - in an afterSign hook, producing a complete signature with sealed resources that Gatekeeper can verify",
                "Release workflow auto-detects whether Developer ID credentials are present; without them it builds an ad-hoc signed DMG instead of failing the \"Require signing and notarization credentials\" gate"
              ]
            },
            {
              "label": "New",
              "items": [
                "docs/INSTALL.md with Homebrew, manual DMG, Windows, and Linux instructions plus the one-line codesign + xattr fix for users on older builds",
                "Homebrew tap at irachrist1/homebrew-daylens so users can brew install --cask irachrist1/daylens/daylens and skip the Gatekeeper dance entirely",
                "build/dmg-README.txt ships inside the mounted DMG so manual-DMG users who never read GitHub still see the fix"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.28",
          "linkLabel": "View release"
        },
        {
          "id": "mac-1.0.27",
          "version": "1.0.27",
          "date": "2026-04-19",
          "title": "Snapshot v2 exports now include recap summaries",
          "intro": [
            "macOS app v1.0.27 centers on snapshot v2 exports now include recap summaries.",
            "Snapshot v2 exports now include recap summaries, focus score v2 breakdowns, work blocks, standout artifacts, entity rollups, and Linux as a first-class snapshot platform for downstream Daylens surfaces.",
            "AI thread naming now uses deterministic intent heuristics for reports, focus flows, and entity questions instead of defaulting to generic prompt fragments."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "Snapshot v2 exports now include recap summaries, focus score v2 breakdowns, work blocks, standout artifacts, entity rollups, and Linux as a first-class snapshot platform for downstream Daylens surfaces",
                "AI thread naming now uses deterministic intent heuristics for reports, focus flows, and entity questions instead of defaulting to generic prompt fragments"
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Monthly recap comparisons now use matched elapsed-day windows so longer months do not invent a gain over shorter previous months",
                "Recap workstream rankings now keep dominant unnamed work visible when attribution is still weak instead of overstating named coverage"
              ]
            },
            {
              "label": "Fixes",
              "items": [
                "Weak AI thread titles now upgrade after the first grounded answer resolves intent, so chats do not stay stuck on New chat or filler-led snippets"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.27",
          "linkLabel": "View release"
        },
        {
          "id": "mac-1.0.26",
          "version": "1.0.26",
          "date": "2026-04-19",
          "title": "Persistent AI threads and artifact storage inside",
          "intro": [
            "macOS app v1.0.26 centers on persistent ai threads and artifact storage inside.",
            "Persistent AI threads and artifact storage inside the AI surface.",
            "A deterministic daily, weekly, and monthly recap card inside the AI surface."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "Persistent AI threads and artifact storage inside the AI surface",
                "A deterministic daily, weekly, and monthly recap card inside the AI surface",
                "Install-flow, onboarding, and shell polish across the shared desktop app"
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Cross-platform parity guidance now reflects the unified desktop repo more honestly across macOS, Windows, and Linux"
              ]
            },
            {
              "label": "Fixes",
              "items": [
                "Shared release notes now keep updater metadata filenames consistent across platform downloads"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.26",
          "linkLabel": "View release"
        }
      ]
    },
    {
      "id": "windows",
      "name": "Windows app",
      "description": "Unified desktop Windows release with shared updater, tracking, recap, and AI behavior.",
      "version": "1.0.30",
      "repoPath": "/Users/tonny/Dev-Personal/daylens",
      "latestCommitDateTime": "2026-04-24T07:21:03+02:00",
      "latestCommitDate": "2026-04-24",
      "latestCommitHash": "970041e",
      "recentCommits": [
        {
          "dateTime": "2026-04-24T07:21:03+02:00",
          "date": "2026-04-24",
          "shortHash": "970041e",
          "subject": "chore(release): prepare v1.0.31"
        },
        {
          "dateTime": "2026-04-24T06:06:21+02:00",
          "date": "2026-04-24",
          "shortHash": "cd771bc",
          "subject": "docs: Add execution plan, codebase overview, and updated product docs"
        },
        {
          "dateTime": "2026-04-24T06:06:15+02:00",
          "date": "2026-04-24",
          "shortHash": "e0c75ae",
          "subject": "feat(updater): Remote update feed with version comparison utilities"
        },
        {
          "dateTime": "2026-04-24T06:06:08+02:00",
          "date": "2026-04-24",
          "shortHash": "3d7ad0e",
          "subject": "feat(threads): Delete artifacts on thread deletion; reuse empty draft threads"
        },
        {
          "dateTime": "2026-04-24T06:05:27+02:00",
          "date": "2026-04-24",
          "shortHash": "897a53d",
          "subject": "feat(search): Add FTS5 search layer (Task A)"
        },
        {
          "dateTime": "2026-04-24T05:09:46+02:00",
          "date": "2026-04-24",
          "shortHash": "3a71389",
          "subject": "Wire onboarding goals into day context"
        },
        {
          "dateTime": "2026-04-24T05:09:28+02:00",
          "date": "2026-04-24",
          "shortHash": "db8f4b5",
          "subject": "Rework focus score v2"
        },
        {
          "dateTime": "2026-04-24T05:09:17+02:00",
          "date": "2026-04-24",
          "shortHash": "e915165",
          "subject": "Wire user name capture"
        },
        {
          "dateTime": "2026-04-23T12:44:49+02:00",
          "date": "2026-04-23",
          "shortHash": "fbef6bb",
          "subject": "chore(release): prepare v1.0.30"
        },
        {
          "dateTime": "2026-04-23T11:14:14+02:00",
          "date": "2026-04-23",
          "shortHash": "149eb7b",
          "subject": "fix(updater): in-place install for ad-hoc macOS + clean HTML release notes"
        }
      ],
      "releases": [
        {
          "id": "windows-1.0.31",
          "version": "1.0.31",
          "date": "2026-04-24",
          "title": "Full-text search across your entire history",
          "intro": [
            "Windows app v1.0.31 centers on full-text search across your entire history.",
            "Full-text search across your entire history — type any word into the new search box in the AI view and get every matching app session, work block, browser page, and AI artifact, sorted by time with highlighted excerpts. No AI involved — pure local SQLite FTS5.",
            "Your name in Daylens — set a display name in onboarding or Settings and the AI will use it in every response instead of the generic fallback."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "Full-text search across your entire history — type any word into the new search box in the AI view and get every matching app session, work block, browser page, and AI artifact, sorted by time with highlighted excerpts. No AI involved — pure local SQLite FTS5.",
                "Your name in Daylens — set a display name in onboarding or Settings and the AI will use it in every response instead of the generic fallback.",
                "Goals now shape your AI context — picking \"less distractions\" during onboarding adds a live distraction summary (minutes + top domains) to every AI response. Picking \"deep work\" adds your deep-work percentage and longest streak."
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Honest focus score — the old formula returned ~20 even on idle days. The new score is a single percentage: time in focused deep-work sessions (25+ continuous minutes) divided by total active time. Returns \"Not enough data\" instead of a fake number when you haven't tracked enough yet.",
                "Thread deletion now removes attached artifact files from disk instead of only cleaning the database row.",
                "Creating a new chat reuses an existing empty thread instead of accumulating blank drafts."
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.31",
          "linkLabel": "View release"
        },
        {
          "id": "windows-1.0.30",
          "version": "1.0.30",
          "date": "2026-04-23",
          "title": "MacOS updates now avoid the broken Squirrel",
          "intro": [
            "Windows app v1.0.30 centers on macos updates now avoid the broken squirrel.",
            "macOS updates now avoid the broken Squirrel.Mac install path on ad-hoc signed builds by downloading the release ZIP directly, swapping the app bundle in place, and relaunching.",
            "Release notes now strip HTML tags cleanly so GitHub-rendered changelog text no longer leaks raw markup into the update banner."
          ],
          "sections": [
            {
              "label": "Fixes",
              "items": [
                "macOS updates now avoid the broken Squirrel.Mac install path on ad-hoc signed builds by downloading the release ZIP directly, swapping the app bundle in place, and relaunching",
                "Release notes now strip HTML tags cleanly so GitHub-rendered changelog text no longer leaks raw markup into the update banner"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.30",
          "linkLabel": "View release"
        },
        {
          "id": "windows-1.0.29",
          "version": "1.0.29",
          "date": "2026-04-20",
          "title": "Rewrote the in-DMG Start Here",
          "intro": [
            "Windows app v1.0.29 centers on rewrote the in-dmg start here.",
            "Rewrote the in-DMG Start Here.txt (formerly If Daylens is \"damaged\" - READ ME.txt) for non-technical users: action-first three-step install, visual mockup of the first-launch Gatekeeper prompt, numbered Open Anyway steps, and Homebrew shown as an optional shortcut rather than the fallback.",
            "docs/INSTALL.md leads with the current first-launch flow (the \"Not Opened\" Gatekeeper prompt that appears after the v1.0.28 ad-hoc re-sign), and demotes the legacy \"damaged\" dialog fix to a troubleshooting section for anyone still on an older DMG."
          ],
          "sections": [
            {
              "label": "Improvements",
              "items": [
                "Rewrote the in-DMG Start Here.txt (formerly If Daylens is \"damaged\" - READ ME.txt) for non-technical users: action-first three-step install, visual mockup of the first-launch Gatekeeper prompt, numbered Open Anyway steps, and Homebrew shown as an optional shortcut rather than the fallback",
                "docs/INSTALL.md leads with the current first-launch flow (the \"Not Opened\" Gatekeeper prompt that appears after the v1.0.28 ad-hoc re-sign), and demotes the legacy \"damaged\" dialog fix to a troubleshooting section for anyone still on an older DMG"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.29",
          "linkLabel": "View release"
        },
        {
          "id": "windows-1.0.28",
          "version": "1.0.28",
          "date": "2026-04-20",
          "title": "MacOS DMG no longer triggers the \"Daylens",
          "intro": [
            "Windows app v1.0.28 centers on macos dmg no longer triggers the \"daylens.",
            "macOS DMG no longer triggers the \"Daylens is damaged and can't be opened\" dialog on Finder double-click: the release pipeline now re-signs the bundle ad-hoc with codesign --force --deep --sign - in an afterSign hook, producing a complete signature with sealed resources that Gatekeeper can verify.",
            "Release workflow auto-detects whether Developer ID credentials are present; without them it builds an ad-hoc signed DMG instead of failing the \"Require signing and notarization credentials\" gate."
          ],
          "sections": [
            {
              "label": "Fixes",
              "items": [
                "macOS DMG no longer triggers the \"Daylens is damaged and can't be opened\" dialog on Finder double-click: the release pipeline now re-signs the bundle ad-hoc with codesign --force --deep --sign - in an afterSign hook, producing a complete signature with sealed resources that Gatekeeper can verify",
                "Release workflow auto-detects whether Developer ID credentials are present; without them it builds an ad-hoc signed DMG instead of failing the \"Require signing and notarization credentials\" gate"
              ]
            },
            {
              "label": "New",
              "items": [
                "docs/INSTALL.md with Homebrew, manual DMG, Windows, and Linux instructions plus the one-line codesign + xattr fix for users on older builds",
                "Homebrew tap at irachrist1/homebrew-daylens so users can brew install --cask irachrist1/daylens/daylens and skip the Gatekeeper dance entirely",
                "build/dmg-README.txt ships inside the mounted DMG so manual-DMG users who never read GitHub still see the fix"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.28",
          "linkLabel": "View release"
        },
        {
          "id": "windows-1.0.27",
          "version": "1.0.27",
          "date": "2026-04-19",
          "title": "Snapshot v2 exports now include recap summaries",
          "intro": [
            "Windows app v1.0.27 centers on snapshot v2 exports now include recap summaries.",
            "Snapshot v2 exports now include recap summaries, focus score v2 breakdowns, work blocks, standout artifacts, entity rollups, and Linux as a first-class snapshot platform for downstream Daylens surfaces.",
            "AI thread naming now uses deterministic intent heuristics for reports, focus flows, and entity questions instead of defaulting to generic prompt fragments."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "Snapshot v2 exports now include recap summaries, focus score v2 breakdowns, work blocks, standout artifacts, entity rollups, and Linux as a first-class snapshot platform for downstream Daylens surfaces",
                "AI thread naming now uses deterministic intent heuristics for reports, focus flows, and entity questions instead of defaulting to generic prompt fragments"
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Monthly recap comparisons now use matched elapsed-day windows so longer months do not invent a gain over shorter previous months",
                "Recap workstream rankings now keep dominant unnamed work visible when attribution is still weak instead of overstating named coverage"
              ]
            },
            {
              "label": "Fixes",
              "items": [
                "Weak AI thread titles now upgrade after the first grounded answer resolves intent, so chats do not stay stuck on New chat or filler-led snippets"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.27",
          "linkLabel": "View release"
        },
        {
          "id": "windows-1.0.26",
          "version": "1.0.26",
          "date": "2026-04-19",
          "title": "Persistent AI threads and artifact storage inside",
          "intro": [
            "Windows app v1.0.26 centers on persistent ai threads and artifact storage inside.",
            "Persistent AI threads and artifact storage inside the AI surface.",
            "A deterministic daily, weekly, and monthly recap card inside the AI surface."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "Persistent AI threads and artifact storage inside the AI surface",
                "A deterministic daily, weekly, and monthly recap card inside the AI surface",
                "Install-flow, onboarding, and shell polish across the shared desktop app"
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Cross-platform parity guidance now reflects the unified desktop repo more honestly across macOS, Windows, and Linux"
              ]
            },
            {
              "label": "Fixes",
              "items": [
                "Shared release notes now keep updater metadata filenames consistent across platform downloads"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.26",
          "linkLabel": "View release"
        }
      ]
    },
    {
      "id": "linux",
      "name": "Linux app",
      "description": "Unified desktop Linux release with AppImage, DEB, and RPM packaging from the shared repo.",
      "version": "1.0.30",
      "repoPath": "/Users/tonny/Dev-Personal/daylens",
      "latestCommitDateTime": "2026-04-24T07:21:03+02:00",
      "latestCommitDate": "2026-04-24",
      "latestCommitHash": "970041e",
      "recentCommits": [
        {
          "dateTime": "2026-04-24T07:21:03+02:00",
          "date": "2026-04-24",
          "shortHash": "970041e",
          "subject": "chore(release): prepare v1.0.31"
        },
        {
          "dateTime": "2026-04-24T06:06:21+02:00",
          "date": "2026-04-24",
          "shortHash": "cd771bc",
          "subject": "docs: Add execution plan, codebase overview, and updated product docs"
        },
        {
          "dateTime": "2026-04-24T06:06:15+02:00",
          "date": "2026-04-24",
          "shortHash": "e0c75ae",
          "subject": "feat(updater): Remote update feed with version comparison utilities"
        },
        {
          "dateTime": "2026-04-24T06:06:08+02:00",
          "date": "2026-04-24",
          "shortHash": "3d7ad0e",
          "subject": "feat(threads): Delete artifacts on thread deletion; reuse empty draft threads"
        },
        {
          "dateTime": "2026-04-24T06:05:27+02:00",
          "date": "2026-04-24",
          "shortHash": "897a53d",
          "subject": "feat(search): Add FTS5 search layer (Task A)"
        },
        {
          "dateTime": "2026-04-24T05:09:46+02:00",
          "date": "2026-04-24",
          "shortHash": "3a71389",
          "subject": "Wire onboarding goals into day context"
        },
        {
          "dateTime": "2026-04-24T05:09:28+02:00",
          "date": "2026-04-24",
          "shortHash": "db8f4b5",
          "subject": "Rework focus score v2"
        },
        {
          "dateTime": "2026-04-24T05:09:17+02:00",
          "date": "2026-04-24",
          "shortHash": "e915165",
          "subject": "Wire user name capture"
        },
        {
          "dateTime": "2026-04-23T12:44:49+02:00",
          "date": "2026-04-23",
          "shortHash": "fbef6bb",
          "subject": "chore(release): prepare v1.0.30"
        },
        {
          "dateTime": "2026-04-23T11:14:14+02:00",
          "date": "2026-04-23",
          "shortHash": "149eb7b",
          "subject": "fix(updater): in-place install for ad-hoc macOS + clean HTML release notes"
        }
      ],
      "releases": [
        {
          "id": "linux-1.0.31",
          "version": "1.0.31",
          "date": "2026-04-24",
          "title": "Full-text search across your entire history",
          "intro": [
            "Linux app v1.0.31 centers on full-text search across your entire history.",
            "Full-text search across your entire history — type any word into the new search box in the AI view and get every matching app session, work block, browser page, and AI artifact, sorted by time with highlighted excerpts. No AI involved — pure local SQLite FTS5.",
            "Your name in Daylens — set a display name in onboarding or Settings and the AI will use it in every response instead of the generic fallback."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "Full-text search across your entire history — type any word into the new search box in the AI view and get every matching app session, work block, browser page, and AI artifact, sorted by time with highlighted excerpts. No AI involved — pure local SQLite FTS5.",
                "Your name in Daylens — set a display name in onboarding or Settings and the AI will use it in every response instead of the generic fallback.",
                "Goals now shape your AI context — picking \"less distractions\" during onboarding adds a live distraction summary (minutes + top domains) to every AI response. Picking \"deep work\" adds your deep-work percentage and longest streak."
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Honest focus score — the old formula returned ~20 even on idle days. The new score is a single percentage: time in focused deep-work sessions (25+ continuous minutes) divided by total active time. Returns \"Not enough data\" instead of a fake number when you haven't tracked enough yet.",
                "Thread deletion now removes attached artifact files from disk instead of only cleaning the database row.",
                "Creating a new chat reuses an existing empty thread instead of accumulating blank drafts."
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.31",
          "linkLabel": "View release"
        },
        {
          "id": "linux-1.0.30",
          "version": "1.0.30",
          "date": "2026-04-23",
          "title": "MacOS updates now avoid the broken Squirrel",
          "intro": [
            "Linux app v1.0.30 centers on macos updates now avoid the broken squirrel.",
            "macOS updates now avoid the broken Squirrel.Mac install path on ad-hoc signed builds by downloading the release ZIP directly, swapping the app bundle in place, and relaunching.",
            "Release notes now strip HTML tags cleanly so GitHub-rendered changelog text no longer leaks raw markup into the update banner."
          ],
          "sections": [
            {
              "label": "Fixes",
              "items": [
                "macOS updates now avoid the broken Squirrel.Mac install path on ad-hoc signed builds by downloading the release ZIP directly, swapping the app bundle in place, and relaunching",
                "Release notes now strip HTML tags cleanly so GitHub-rendered changelog text no longer leaks raw markup into the update banner"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.30",
          "linkLabel": "View release"
        },
        {
          "id": "linux-1.0.29",
          "version": "1.0.29",
          "date": "2026-04-20",
          "title": "Rewrote the in-DMG Start Here",
          "intro": [
            "Linux app v1.0.29 centers on rewrote the in-dmg start here.",
            "Rewrote the in-DMG Start Here.txt (formerly If Daylens is \"damaged\" - READ ME.txt) for non-technical users: action-first three-step install, visual mockup of the first-launch Gatekeeper prompt, numbered Open Anyway steps, and Homebrew shown as an optional shortcut rather than the fallback.",
            "docs/INSTALL.md leads with the current first-launch flow (the \"Not Opened\" Gatekeeper prompt that appears after the v1.0.28 ad-hoc re-sign), and demotes the legacy \"damaged\" dialog fix to a troubleshooting section for anyone still on an older DMG."
          ],
          "sections": [
            {
              "label": "Improvements",
              "items": [
                "Rewrote the in-DMG Start Here.txt (formerly If Daylens is \"damaged\" - READ ME.txt) for non-technical users: action-first three-step install, visual mockup of the first-launch Gatekeeper prompt, numbered Open Anyway steps, and Homebrew shown as an optional shortcut rather than the fallback",
                "docs/INSTALL.md leads with the current first-launch flow (the \"Not Opened\" Gatekeeper prompt that appears after the v1.0.28 ad-hoc re-sign), and demotes the legacy \"damaged\" dialog fix to a troubleshooting section for anyone still on an older DMG"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.29",
          "linkLabel": "View release"
        },
        {
          "id": "linux-1.0.28",
          "version": "1.0.28",
          "date": "2026-04-20",
          "title": "MacOS DMG no longer triggers the \"Daylens",
          "intro": [
            "Linux app v1.0.28 centers on macos dmg no longer triggers the \"daylens.",
            "macOS DMG no longer triggers the \"Daylens is damaged and can't be opened\" dialog on Finder double-click: the release pipeline now re-signs the bundle ad-hoc with codesign --force --deep --sign - in an afterSign hook, producing a complete signature with sealed resources that Gatekeeper can verify.",
            "Release workflow auto-detects whether Developer ID credentials are present; without them it builds an ad-hoc signed DMG instead of failing the \"Require signing and notarization credentials\" gate."
          ],
          "sections": [
            {
              "label": "Fixes",
              "items": [
                "macOS DMG no longer triggers the \"Daylens is damaged and can't be opened\" dialog on Finder double-click: the release pipeline now re-signs the bundle ad-hoc with codesign --force --deep --sign - in an afterSign hook, producing a complete signature with sealed resources that Gatekeeper can verify",
                "Release workflow auto-detects whether Developer ID credentials are present; without them it builds an ad-hoc signed DMG instead of failing the \"Require signing and notarization credentials\" gate"
              ]
            },
            {
              "label": "New",
              "items": [
                "docs/INSTALL.md with Homebrew, manual DMG, Windows, and Linux instructions plus the one-line codesign + xattr fix for users on older builds",
                "Homebrew tap at irachrist1/homebrew-daylens so users can brew install --cask irachrist1/daylens/daylens and skip the Gatekeeper dance entirely",
                "build/dmg-README.txt ships inside the mounted DMG so manual-DMG users who never read GitHub still see the fix"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.28",
          "linkLabel": "View release"
        },
        {
          "id": "linux-1.0.27",
          "version": "1.0.27",
          "date": "2026-04-19",
          "title": "Snapshot v2 exports now include recap summaries",
          "intro": [
            "Linux app v1.0.27 centers on snapshot v2 exports now include recap summaries.",
            "Snapshot v2 exports now include recap summaries, focus score v2 breakdowns, work blocks, standout artifacts, entity rollups, and Linux as a first-class snapshot platform for downstream Daylens surfaces.",
            "AI thread naming now uses deterministic intent heuristics for reports, focus flows, and entity questions instead of defaulting to generic prompt fragments."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "Snapshot v2 exports now include recap summaries, focus score v2 breakdowns, work blocks, standout artifacts, entity rollups, and Linux as a first-class snapshot platform for downstream Daylens surfaces",
                "AI thread naming now uses deterministic intent heuristics for reports, focus flows, and entity questions instead of defaulting to generic prompt fragments"
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Monthly recap comparisons now use matched elapsed-day windows so longer months do not invent a gain over shorter previous months",
                "Recap workstream rankings now keep dominant unnamed work visible when attribution is still weak instead of overstating named coverage"
              ]
            },
            {
              "label": "Fixes",
              "items": [
                "Weak AI thread titles now upgrade after the first grounded answer resolves intent, so chats do not stay stuck on New chat or filler-led snippets"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.27",
          "linkLabel": "View release"
        },
        {
          "id": "linux-1.0.26",
          "version": "1.0.26",
          "date": "2026-04-19",
          "title": "Persistent AI threads and artifact storage inside",
          "intro": [
            "Linux app v1.0.26 centers on persistent ai threads and artifact storage inside.",
            "Persistent AI threads and artifact storage inside the AI surface.",
            "A deterministic daily, weekly, and monthly recap card inside the AI surface."
          ],
          "sections": [
            {
              "label": "New",
              "items": [
                "Persistent AI threads and artifact storage inside the AI surface",
                "A deterministic daily, weekly, and monthly recap card inside the AI surface",
                "Install-flow, onboarding, and shell polish across the shared desktop app"
              ]
            },
            {
              "label": "Improvements",
              "items": [
                "Cross-platform parity guidance now reflects the unified desktop repo more honestly across macOS, Windows, and Linux"
              ]
            },
            {
              "label": "Fixes",
              "items": [
                "Shared release notes now keep updater metadata filenames consistent across platform downloads"
              ]
            }
          ],
          "linkUrl": "https://github.com/irachrist1/daylens/releases/tag/v1.0.26",
          "linkLabel": "View release"
        }
      ]
    }
  ]
} as const;
